// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function OpenOutputDir() {
  return window['go']['main']['App']['OpenOutputDir']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PickOutputDir() {
  return window['go']['main']['App']['PickOutputDir']();
}

export function StartJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartJob'](arg1, arg2, arg3, arg4);
}
