// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function GetStatus(arg1:string):Promise<app.StatusUpdate>;

export function OpenOutputDir():Promise<void>;

export function PickFile():Promise<string>;

export function PickOutputDir():Promise<string>;

export function StartJob(arg1:string,arg2:number,arg3:number,arg4:string):Promise<string>;
